### ISSUE TITLE
Will not build with GHC 8.8

### ISSUE THREAD

**Issue by kozross** [sjakobi/coercible-utils#20]
The ``base < 4.13`` constraint prevents this currently. If you use ``--allow-newer``, everything works though.

**Comment by chessai** [comment]
Im on mobile. Perhaps send a PR this way? :)

**Comment by treeowl** [comment]
Are there Hackage bounds we can relax too?

**Comment by sjakobi** [comment]
I've just made a Hackage revision to allow building with GHC-8.8. I'll try to make a proper new release this weekend or early next week.

**Comment by kozross** [comment]
This issue seems to be resolved, especially given the new release, so I'll close it.
