### ISSUE TITLE
might be worthwhile to point users to the hashtag-coerce ghc-plugin

### ISSUE THREAD

**Issue by chessai** [sjakobi/coercible-utils#4]
https://github.com/mpickering/hashtag-coerce

hashtag-coerce is a GHC plugin which could potentially be a very good mix with this library. The reason I say this is that yes, while something like

```haskell
ala :: (Coercible a b, Coercible a' b')
      => (a -> b)
      -> ((a -> b) -> c -> b')
      -> c
      -> a'
```

is most certainly very useful, it is perhaps not the most 'recognisable'. By 'recognisable', I mean that it might be difficult for a programmer to recognise their ability to use this function (which would usually arise by replacing code that performs manual transformations with `ala`). Especially with some of the larger (in type signature) coercible-utils! That is why I think it might be a good idea to use that plugin in addition to this library.

**Comment by sjakobi** [comment]
Oh cool, I hadn't heard of this before.

We should add a reference in the haddocks.

**Comment by chessai** [comment]
Actually, this isn't worthwhile for the moment. It only detects things like 'map coerce'.
